AWSTemplateFormatVersion: '2010-09-09'
Description: Create ECR

Parameters:
  ProjectName:
    Type: String

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-ecr

Outputs:
  ECR:
    Value: !GetAtt ECR.RepositoryUri
    Export:
      Name: !Sub ${ProjectName}-ecr-repository-uri
