name: Push Image to ECR

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
          - stg

jobs:
  push_image_to_ecr:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: ${{ github.event.inputs.target-env }}-souharu
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183816441:role/Github-action
          aws-region: ap-northeast-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Output image details
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Image url: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
